version: '3'
services:
  test:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    command:
      npm run mocha
    links:
      - redis
      - telegraf
  redis:
    image: redis
  telegraf:
    image: telegraf
